apiVersion: v1
kind: Secret
metadata:
  name: apicurio-secret
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc }}
  db-root-password: {{ .Values.database.rootPassword | b64enc }}
  db-user: {{ .Values.database.user | b64enc }}
  apicurio-kc-client-secret: {{ .Values.keycloak.client.secret | b64enc }}
  apicurio-microcks-client-secret: {{ .Values.microcks.client.secret | b64enc }}
