apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    module: {{ .Values.database.name }}
  name: {{ .Values.database.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      module: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        module: {{ .Values.database.name }}
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.database.schema }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: apicurio-secret
                  key: db-user
          image: {{ .Values.database.image }}
          imagePullPolicy: {{ .Values.database.imagePullPolicy }}
          name: {{ .Values.database.name }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-apicurio
      restartPolicy: Always
      volumes:
        - name: mysql-apicurio
          persistentVolumeClaim:
            claimName: apicuriodata
        - name: apicurio-secret
          secret:
            secretName: apicurio-secret
